# Generated by Django 4.2.3 on 2024-09-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('value', models.FloatField()),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('fulfilled_at', models.DateField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PencilBoxLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PencilBoxLocationInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_number', models.IntegerField()),
                ('low_stock', models.IntegerField()),
                ('max_amt', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('in_stock', models.IntegerField()),
                ('last_audited', models.DateTimeField()),
                ('archived', models.BooleanField(default=False)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pencil_box_locations', to='admin_app.inventoryitem')),
                ('pencil_box_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='admin_app.pencilboxlocation')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopper_qty', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('pencil_box_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='admin_app.pencilboxlocation')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('sales_force_id', models.CharField(blank=True, max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='admin_app.county')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=55)),
                ('pencil_id', models.IntegerField()),
                ('archived', models.BooleanField(default=False)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_app.county')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='admin_app.school')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.order')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_app.scheduleitem')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PencilBoxLocationInventoryItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.order')),
                ('pencil_box_location_inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_app.pencilboxlocationinventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_orders', to='admin_app.school'),
        ),
        migrations.AddField(
            model_name='order',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='admin_app.teacher'),
        ),
        migrations.CreateModel(
            name='InventoryIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(max_length=255)),
                ('donated_by', models.CharField(max_length=255)),
                ('qty_donated', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('updated_at', models.DateTimeField()),
                ('intake_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_app.intaketype')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='admin_app.inventoryitem')),
                ('pencil_box_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_app.pencilboxlocation')),
            ],
        ),
    ]
