# Generated by Django 4.2.3 on 2024-09-12 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfilled_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherscheduleitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.order'),
        ),
    ]
